### PR TITLE
set up chrony to use amazon time sync

### PR DESCRIPTION
**Pull request by lucy-lufei**
@sinneduy and I validated that this set up chrony to use Amazon Time Sync:

```
ubuntu@ip-10-10-75-99:~$ cat /etc/chrony/chrony.conf
server 169.254.169.123 prefer iburst minpoll 4 maxpoll 4
# Welcome to the chrony configuration file. See chrony.conf(5) for more
# information about usuable directives.

# This will use (up to):
# - 4 sources from ntp.ubuntu.com which some are ipv6 enabled
# - 2 sources from 2.ubuntu.pool.ntp.org which is ipv6 enabled as well
# - 1 source from [01].ubuntu.pool.ntp.org each (ipv4 only atm)
# This means by default, up to 6 dual-stack and up to 2 additional IPv4-only
# sources will be used.
# At the same time it retains some protection against one of the entries being
# down (compare to just using one of the lines). See (LP: #1754358) for the
# discussion.
#
# About using servers from the NTP Pool Project in general see (LP: #104525).
# Approved by Ubuntu Technical Board on 2011-02-08.
# See http://www.pool.ntp.org/join.html for more information.
pool ntp.ubuntu.com        iburst maxsources 4
pool 0.ubuntu.pool.ntp.org iburst maxsources 1
pool 1.ubuntu.pool.ntp.org iburst maxsources 1
pool 2.ubuntu.pool.ntp.org iburst maxsources 2

# This directive specify the location of the file containing ID/key pairs for
# NTP authentication.
keyfile /etc/chrony/chrony.keys

# This directive specify the file into which chronyd will store the rate
# information.
driftfile /var/lib/chrony/chrony.drift

# Uncomment the following line to turn logging on.
#log tracking measurements statistics

# Log files location.
logdir /var/log/chrony

# Stop bad estimates upsetting machine clock.
maxupdateskew 100.0

# This directive enables kernel synchronisation (every 11 minutes) of the
# real-time clock. Note that it can’t be used along with the 'rtcfile' directive.
rtcsync

# Step the system clock instead of slewing it if the adjustment is larger than
# one second, but only in the first three clock updates.
makestep 1 3
ubuntu@ip-10-10-75-99:~$ chronyc sources -v
210 Number of sources = 1

  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current synced, '+' = combined , '-' = not combined,
| /   '?' = unreachable, 'x' = time may be in error, '~' = time too variable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^* 169.254.169.123               3   4   177     3  -8825ns[ -115us] +/-  218us
```

However, its pretty weird that it doesn't have any other ips to pool from - do you think that's okay?

cc @szarya 

When we added the Amazon Time to an already running instance, we saw that it had the Amazon Time Sync server as preferred, but still had a number of other servers listed (as backup maybe?)

```
lucy.lufei@eks-payroll-staging-i-0285d2ee3cf56ad5b:~$ chronyc sources -v
210 Number of sources = 9

  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current synced, '+' = combined , '-' = not combined,
| /   '?' = unreachable, 'x' = time may be in error, '~' = time too variable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^* 169.254.169.123               3   4   377    14  -7149ns[-6446ns] +/-  135us
^- pugot.canonical.com           2   6   357    63  -1540us[-1539us] +/-  122ms
^- alphyn.canonical.com          2   6   377    66  -1128us[-1127us] +/-  110ms
^- chilipepper.canonical.com     2   6   356   258  -1487us[-1482us] +/-  107ms
^- golem.canonical.com           2   6   377    64  -1585us[-1584us] +/-   99ms
^- jitter.tickadj.net            2   6   377    65   -491us[ -490us] +/-   51ms
^- ellone.fdisk.io               2   6   377    64   +162us[ +163us] +/-   36ms
^- gw1.rbx.ip4.servme.fr         3   6   377    63  -1194us[-1193us] +/-  188ms
^- zero.gotroot.ca               2   6   377     1  -1818us[-1818us] +/-   16ms
```

### CODE REVIEW

**Comment by hposca** [comment]
> However, its pretty weird that it doesn't have any other ips to pool from - do you think that's okay?

Ideally we could use more. But if `169.254.169.123` is not available AWS will be having another problems.

**Comment by szarya** [comment]
I'm not sure amazon consider ntp a tier 0 service, so ntp might be down at some point.
Still, it's more reliable than sending udp to the other side of the world (as some of those servers are trying to do). Is it hard to manually add ntp.ubuntu.com as a backup?

**Comment by sinneduy** [comment]
in the current configuration, other ntp pools are in the configuration, they just aren't being used... its possible that they'll come into play if amazon time sync fails...

**Comment by sinneduy** [comment]
Okay, it turns out the reason for this is that there isn't DNS on the EKS node by default (as per the AWS AMI setup).

```
ubuntu@ip-10-10-72-10:~$ curl ntp.ubuntu.com
curl: (6) Could not resolve host: ntp.ubuntu.com
ubuntu@ip-10-10-72-10:~$ curl google.com
curl: (6) Could not resolve host: google.com
ubuntu@ip-10-10-72-10:~$ sudo vim /etc/chrony/chrony.conf
sudo: unable to resolve host ip-10-10-72-10: Resource temporarily unavailable
ubuntu@ip-10-10-72-10:~$ sudo service chrony restart
sudo: unable to resolve host ip-10-10-72-10: Resource temporarily unavailable
ubuntu@ip-10-10-72-10:~$ chronyc sources -v
210 Number of sources = 2

  .-- Source mode  '^' = server, '=' = peer, '#' = local clock.
 / .- Source state '*' = current synced, '+' = combined , '-' = not combined,
| /   '?' = unreachable, 'x' = time may be in error, '~' = time too variable.
||                                                 .- xxxx [ yyyy ] +/- zzzz
||      Reachability register (octal) -.           |  xxxx = adjusted offset,
||      Log2(Polling interval) --.      |          |  yyyy = measured offset,
||                                \     |          |  zzzz = estimated error.
||                                 |    |           \
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^? 169.254.169.123               3   4     1     2  -2733ns[-2733ns] +/-  304us
^? 169.254.169.122               0   6     0     -     +0ns[   +0ns] +/-    0ns
ubuntu@ip-10-10-72-10:~$ exit
```

When I added a direct ip to use separately, this was fine.  Thus, I'm going to merge this in

**Pull request merged**
